/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.awt.Color;
import java.awt.Desktop;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author jorgi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(this);
        
        if (txt_user.getText().length()==0) {
            String usuario;
            usuario = "No ha ingresado usuario";
            txt_user.setText(usuario);
        }
        if (txt_pass.getText().length()==0) {
            txt_pass.setForeground(Color.GRAY);
            String usuario;
            usuario = "No ha ingresado contrasena";
            txt_pass.setText(usuario);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnl_menu = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txt_user = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        txt_pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_menu = new javax.swing.JButton();
        btn_cerrar = new javax.swing.JButton();
        pnl_registro = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        txt_nombrereg = new javax.swing.JTextField();
        txt_segnombrereg = new javax.swing.JTextField();
        txt_apereg = new javax.swing.JTextField();
        txt_segapegreg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel_MantenimientosP = new javax.swing.JPanel();
        jLabel_ID_Puesto = new javax.swing.JLabel();
        txt_id_Puesto = new javax.swing.JTextField();
        jLabel_Nombre_Puesto = new javax.swing.JLabel();
        txt_Nombre_Puesto = new javax.swing.JTextField();
        jLabel_Descripcion_Puesto = new javax.swing.JLabel();
        jLabel_Descripcion_Puesto1 = new javax.swing.JLabel();
        txt_Estatus_Puesto = new javax.swing.JTextField();
        jScrollPane22 = new javax.swing.JScrollPane();
        tbl_Puesto = new javax.swing.JTable();
        jLabel_Buscar_Puesto = new javax.swing.JLabel();
        txt_Buscar_Puesto = new javax.swing.JTextField();
        jLabel_Insertar_Puesto = new javax.swing.JLabel();
        jLabel_Modificar_Puesto = new javax.swing.JLabel();
        jLabel_Eliminar_Puesto = new javax.swing.JLabel();
        Panel_IngresarP = new javax.swing.JPanel();
        Texto_IngresarP = new javax.swing.JLabel();
        Panel_ModificarP = new javax.swing.JPanel();
        Texto_ModificarP = new javax.swing.JLabel();
        Panel_EliminarP = new javax.swing.JPanel();
        Texto_EliminarP = new javax.swing.JLabel();
        Panel_ConsultarP = new javax.swing.JPanel();
        Texto_ConsultarP = new javax.swing.JLabel();
        jLabel_TituloD1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_Descripcion_Puesto = new javax.swing.JTextArea();
        icono_Buscar1 = new javax.swing.JLabel();
        jLabel_TituloD2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(28, 27, 33));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 5));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnl_menu.setBackground(new java.awt.Color(28, 27, 33));
        pnl_menu.setBorder(javax.swing.BorderFactory.createLineBorder(java.awt.SystemColor.controlDkShadow, 3));
        pnl_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(28, 27, 33));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/123445.png"))); // NOI18N
        pnl_menu.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, -1, 90));

        txt_user.setBackground(new java.awt.Color(51, 51, 51));
        txt_user.setForeground(new java.awt.Color(204, 204, 204));
        txt_user.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_user.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txt_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_userMouseClicked(evt);
            }
        });
        txt_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_userActionPerformed(evt);
            }
        });
        txt_user.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_userKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_userKeyTyped(evt);
            }
        });
        pnl_menu.add(txt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 162, 190, 20));

        jButton5.setBackground(new java.awt.Color(28, 27, 33));
        jButton5.setFont(new java.awt.Font("Century Schoolbook", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Ingresar_D.png"))); // NOI18N
        jButton5.setBorder(null);
        jButton5.setContentAreaFilled(false);
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.setFocusPainted(false);
        jButton5.setOpaque(true);
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        pnl_menu.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 260, -1, -1));

        txt_pass.setBackground(new java.awt.Color(51, 51, 51));
        txt_pass.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        txt_pass.setPreferredSize(new java.awt.Dimension(9, 34));
        txt_pass.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_passMouseClicked(evt);
            }
        });
        txt_pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_passActionPerformed(evt);
            }
        });
        txt_pass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_passKeyTyped(evt);
            }
        });
        pnl_menu.add(txt_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(13, 228, 190, 20));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/face.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        pnl_menu.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ing.png"))); // NOI18N
        pnl_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/yt.png"))); // NOI18N
        pnl_menu.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("INGRESE USUARIO");
        pnl_menu.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("INGRESE CONTRASENA");
        pnl_menu.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 200, -1, -1));

        jPanel1.add(pnl_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(-235, 5, -1, -1));

        btn_menu.setBackground(new java.awt.Color(28, 27, 33));
        btn_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Logo.png"))); // NOI18N
        btn_menu.setBorder(null);
        btn_menu.setBorderPainted(false);
        btn_menu.setContentAreaFilled(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.setFocusPainted(false);
        btn_menu.setVerifyInputWhenFocusTarget(false);
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_menuMouseClicked(evt);
            }
        });
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });
        jPanel1.add(btn_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(5, 5, 69, 73));
        btn_menu.getAccessibleContext().setAccessibleDescription("");

        btn_cerrar.setBackground(new java.awt.Color(255, 0, 51));
        btn_cerrar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btn_cerrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_cerrar.setText("X");
        btn_cerrar.setBorder(null);
        btn_cerrar.setContentAreaFilled(false);
        btn_cerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_cerrar.setOpaque(true);
        btn_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btn_cerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 0, 43, -1));

        pnl_registro.setBackground(new java.awt.Color(28, 27, 33));
        pnl_registro.setMaximumSize(new java.awt.Dimension(448, 326));
        pnl_registro.setPreferredSize(new java.awt.Dimension(448, 326));

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator2.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator3.setForeground(new java.awt.Color(255, 255, 255));

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        txt_nombrereg.setBackground(new java.awt.Color(204, 204, 204));
        txt_nombrereg.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_nombrereg.setCaretColor(new java.awt.Color(255, 255, 255));

        txt_segnombrereg.setBackground(new java.awt.Color(204, 204, 204));
        txt_segnombrereg.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Segundo Nombre:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txt_apereg.setBackground(new java.awt.Color(204, 204, 204));
        txt_apereg.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Primer Apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N

        txt_segapegreg.setBackground(new java.awt.Color(204, 204, 204));
        txt_segapegreg.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1), "Segundo apellido:", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(255, 255, 255))); // NOI18N
        txt_segapegreg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_segapegregActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("R E G I S T R O    D E    N U E V O S     U S U A R I O S");

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/PEPEE.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/USER.png"))); // NOI18N

        javax.swing.GroupLayout pnl_registroLayout = new javax.swing.GroupLayout(pnl_registro);
        pnl_registro.setLayout(pnl_registroLayout);
        pnl_registroLayout.setHorizontalGroup(
            pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registroLayout.createSequentialGroup()
                .addGroup(pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel4))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(190, 190, 190)
                        .addComponent(jLabel8))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txt_nombrereg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(txt_segnombrereg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(txt_apereg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(txt_segapegreg, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_registroLayout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel9)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl_registroLayout.setVerticalGroup(
            pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_registroLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jLabel8)
                .addGroup(pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_nombrereg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_segnombrereg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_apereg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_segapegreg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnl_registroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(pnl_registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(-800, 5, 448, 326));
        pnl_registro.getAccessibleContext().setAccessibleDescription("");

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("JORGE LIZANDRO CASTANEDA CHOY");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("9959 - 18 - 4964.");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jPanel_MantenimientosP.setBackground(new java.awt.Color(28, 27, 33));
        jPanel_MantenimientosP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_ID_Puesto.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_ID_Puesto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ID_Puesto.setText("ID Puesto");
        jPanel_MantenimientosP.add(jLabel_ID_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, -1, -1));

        txt_id_Puesto.setBackground(new java.awt.Color(40, 41, 46));
        txt_id_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_id_Puesto.setBorder(null);
        txt_id_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_id_PuestoActionPerformed(evt);
            }
        });
        jPanel_MantenimientosP.add(txt_id_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, 140, 20));

        jLabel_Nombre_Puesto.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre_Puesto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Nombre_Puesto.setText("Nombre Puesto");
        jPanel_MantenimientosP.add(jLabel_Nombre_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, -1, -1));

        txt_Nombre_Puesto.setBackground(new java.awt.Color(40, 41, 46));
        txt_Nombre_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_Nombre_Puesto.setBorder(null);
        txt_Nombre_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Nombre_PuestoActionPerformed(evt);
            }
        });
        jPanel_MantenimientosP.add(txt_Nombre_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 140, 20));

        jLabel_Descripcion_Puesto.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Descripcion_Puesto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Descripcion_Puesto.setText("Descripcion Puesto");
        jPanel_MantenimientosP.add(jLabel_Descripcion_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, -1, -1));

        jLabel_Descripcion_Puesto1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Descripcion_Puesto1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Descripcion_Puesto1.setText("Estatus Puesto");
        jPanel_MantenimientosP.add(jLabel_Descripcion_Puesto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, -1, -1));

        txt_Estatus_Puesto.setBackground(new java.awt.Color(40, 41, 46));
        txt_Estatus_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_Estatus_Puesto.setBorder(null);
        txt_Estatus_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Estatus_PuestoActionPerformed(evt);
            }
        });
        jPanel_MantenimientosP.add(txt_Estatus_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 360, 140, 20));

        tbl_Puesto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbl_Puesto.setGridColor(new java.awt.Color(255, 255, 255));
        tbl_Puesto.setSelectionBackground(new java.awt.Color(40, 41, 46));
        tbl_Puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_PuestoMouseClicked(evt);
            }
        });
        jScrollPane22.setViewportView(tbl_Puesto);

        jPanel_MantenimientosP.add(jScrollPane22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 540, 600, 190));

        jLabel_Buscar_Puesto.setBackground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_Puesto.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Buscar_Puesto.setText("Buscar");
        jPanel_MantenimientosP.add(jLabel_Buscar_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 490, -1, -1));

        txt_Buscar_Puesto.setBackground(new java.awt.Color(40, 41, 46));
        txt_Buscar_Puesto.setForeground(new java.awt.Color(153, 153, 153));
        txt_Buscar_Puesto.setBorder(null);
        txt_Buscar_Puesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_Buscar_PuestoActionPerformed(evt);
            }
        });
        txt_Buscar_Puesto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_Buscar_PuestoKeyReleased(evt);
            }
        });
        jPanel_MantenimientosP.add(txt_Buscar_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 490, 290, 20));

        jLabel_Insertar_Puesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Insertar_Puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Insertar_PuestoMouseClicked(evt);
            }
        });
        jPanel_MantenimientosP.add(jLabel_Insertar_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, -1, -1));

        jLabel_Modificar_Puesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Modificar_Puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Modificar_PuestoMouseClicked(evt);
            }
        });
        jPanel_MantenimientosP.add(jLabel_Modificar_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, -1, -1));

        jLabel_Eliminar_Puesto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Eliminar_Puesto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_Eliminar_PuestoMouseClicked(evt);
            }
        });
        jPanel_MantenimientosP.add(jLabel_Eliminar_Puesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 470, -1, -1));

        Panel_IngresarP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_IngresarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_IngresarPMouseClicked(evt);
            }
        });
        Panel_IngresarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_IngresarP.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        Texto_IngresarP.setForeground(new java.awt.Color(255, 255, 255));
        Texto_IngresarP.setText("Ingresar");
        Texto_IngresarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Texto_IngresarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto_IngresarPMouseClicked(evt);
            }
        });
        Panel_IngresarP.add(Texto_IngresarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 15, -1, -1));

        jPanel_MantenimientosP.add(Panel_IngresarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 130, 50));

        Panel_ModificarP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_ModificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Panel_ModificarPMouseClicked(evt);
            }
        });
        Panel_ModificarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_ModificarP.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        Texto_ModificarP.setForeground(new java.awt.Color(255, 255, 255));
        Texto_ModificarP.setText("Modificar");
        Texto_ModificarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Texto_ModificarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto_ModificarPMouseClicked(evt);
            }
        });
        Panel_ModificarP.add(Texto_ModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 15, -1, -1));

        jPanel_MantenimientosP.add(Panel_ModificarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 220, 130, 50));

        Panel_EliminarP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_EliminarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_EliminarP.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        Texto_EliminarP.setForeground(new java.awt.Color(255, 255, 255));
        Texto_EliminarP.setText("Eliminar");
        Texto_EliminarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Texto_EliminarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto_EliminarPMouseClicked(evt);
            }
        });
        Panel_EliminarP.add(Texto_EliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 15, -1, -1));

        jPanel_MantenimientosP.add(Panel_EliminarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, 130, 50));

        Panel_ConsultarP.setBackground(new java.awt.Color(28, 27, 33));
        Panel_ConsultarP.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Texto_ConsultarP.setFont(new java.awt.Font("Open Sans SemiBold", 0, 14)); // NOI18N
        Texto_ConsultarP.setForeground(new java.awt.Color(255, 255, 255));
        Texto_ConsultarP.setText("Consultar");
        Texto_ConsultarP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Texto_ConsultarP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Texto_ConsultarPMouseClicked(evt);
            }
        });
        Panel_ConsultarP.add(Texto_ConsultarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 15, -1, -1));

        jPanel_MantenimientosP.add(Panel_ConsultarP, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 130, 50));

        jLabel_TituloD1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Titulo Puesto.png"))); // NOI18N
        jPanel_MantenimientosP.add(jLabel_TituloD1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 400, 120));

        txt_Descripcion_Puesto.setBackground(new java.awt.Color(40, 41, 46));
        txt_Descripcion_Puesto.setColumns(20);
        txt_Descripcion_Puesto.setForeground(new java.awt.Color(255, 255, 255));
        txt_Descripcion_Puesto.setRows(5);
        txt_Descripcion_Puesto.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        jScrollPane2.setViewportView(txt_Descripcion_Puesto);

        jPanel_MantenimientosP.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 360, 190, -1));
        jPanel_MantenimientosP.add(icono_Buscar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 490, 20, 20));
        jPanel_MantenimientosP.add(jLabel_TituloD2, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 400, 120));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_MantenimientosP, javax.swing.GroupLayout.PREFERRED_SIZE, 1140, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel_MantenimientosP, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_cerrarActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        // TODO add your handling code here:
        int posicion = btn_menu.getX();
        if (posicion>5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btn_menu);
            Animacion.Animacion.mover_izquierda(5, -245, 2, 2, pnl_menu);
        }
        else
        {
            Animacion.Animacion.mover_derecha(5, 235, 2, 2, btn_menu);
            Animacion.Animacion.mover_derecha(-210, 5, 2, 2, pnl_menu); 
        }
    }//GEN-LAST:event_btn_menuActionPerformed

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        MDI_JORGE_CASTANEDA9959184964 md = new MDI_JORGE_CASTANEDA9959184964();
        Principal p = new Principal();
        md.setVisible(true);
        
    }//GEN-LAST:event_jButton5MouseClicked

    private void txt_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_userActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_userActionPerformed

    private void txt_userKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyTyped
        // TODO add your handling code here:
        txt_user.setForeground(Color.black);
    }//GEN-LAST:event_txt_userKeyTyped

    private void txt_userKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_userKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txt_userKeyPressed

    private void txt_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_userMouseClicked
        // TODO add your handling code here:
        txt_user.setText("");    
        
    }//GEN-LAST:event_txt_userMouseClicked

    private void txt_passMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_passMouseClicked
        // TODO add your handling code here:
        txt_pass.setText("");
    }//GEN-LAST:event_txt_passMouseClicked

    private void txt_passKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_passKeyTyped
        // TODO add your handling code here:
        txt_pass.setForeground(Color.black);
    }//GEN-LAST:event_txt_passKeyTyped

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel5MouseClicked

    private void txt_passActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_passActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_passActionPerformed

    private void txt_segapegregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_segapegregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_segapegregActionPerformed

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        int posicion = btn_menu.getX();
        if (posicion>5) {
            Animacion.Animacion.mover_izquierda(211, 5, 2, 2, btn_menu);
            Animacion.Animacion.mover_izquierda(5, -245, 2, 2, pnl_menu);
        }
        else
        {
            Animacion.Animacion.mover_derecha(5, 235, 2, 2, btn_menu);
            Animacion.Animacion.mover_derecha(-210, 5, 2, 2, pnl_menu); 
        }
        
        int posi = pnl_registro.getX();
        if (posi>5) {
           Animacion.Animacion.subir(800, -1100, 2, 2, pnl_registro);

        }
        else
        {
            Animacion.Animacion.mover_derecha(5, 235, 2, 2, btn_menu);
            Animacion.Animacion.mover_derecha(-210, 5, 2, 2, pnl_menu); 

        }
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void btn_menuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_menuMouseClicked

    private void txt_id_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_id_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_id_PuestoActionPerformed

    private void txt_Nombre_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Nombre_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Nombre_PuestoActionPerformed

    private void txt_Estatus_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Estatus_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Estatus_PuestoActionPerformed

    private void tbl_PuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_PuestoMouseClicked
        // TODO add your handling code here:
        int Seleccion = tbl_Puesto.rowAtPoint(evt.getPoint());
        txt_id_Puesto.setText(String.valueOf(tbl_Puesto.getValueAt(Seleccion, 0)));
        txt_Nombre_Puesto.setText(String.valueOf(tbl_Puesto.getValueAt(Seleccion, 1)));
        txt_Descripcion_Puesto.setText(String.valueOf(tbl_Puesto.getValueAt(Seleccion, 2)));
        txt_Estatus_Puesto.setText(String.valueOf(tbl_Puesto.getValueAt(Seleccion, 3)));
    }//GEN-LAST:event_tbl_PuestoMouseClicked

    private void txt_Buscar_PuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_Buscar_PuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_Buscar_PuestoActionPerformed

    private void txt_Buscar_PuestoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_Buscar_PuestoKeyReleased
        // TODO add your handling code here:
        //Puesto puesto = new Puesto(txt_id_Puesto, txt_Nombre_Puesto, txt_Descripcion_Puesto, txt_Estatus_Puesto, txt_Buscar_Puesto, tbl_Puesto);
        //puesto.Buscar_PuestoF(txt_Buscar_Puesto.getText());
    }//GEN-LAST:event_txt_Buscar_PuestoKeyReleased

    private void jLabel_Insertar_PuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Insertar_PuestoMouseClicked
        // TODO add your handling code here:
        //Puesto puesto = new Puesto(txt_id_Puesto, txt_Nombre_Puesto, txt_Descripcion_Puesto, txt_Estatus_Puesto, txt_Buscar_Puesto, tbl_Puesto);
        //puesto.Insertar_Puesto();
    }//GEN-LAST:event_jLabel_Insertar_PuestoMouseClicked

    private void jLabel_Modificar_PuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Modificar_PuestoMouseClicked
        // TODO add your handling code here:
        //Puesto puesto = new Puesto(txt_id_Puesto, txt_Nombre_Puesto, txt_Descripcion_Puesto, txt_Estatus_Puesto, txt_Buscar_Puesto, tbl_Puesto);
        //puesto.Modificar_Puesto();
    }//GEN-LAST:event_jLabel_Modificar_PuestoMouseClicked

    private void jLabel_Eliminar_PuestoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_Eliminar_PuestoMouseClicked
        // TODO add your handling code here:
        //Puesto puesto = new Puesto(txt_id_Puesto, txt_Nombre_Puesto, txt_Descripcion_Puesto, txt_Estatus_Puesto, txt_Buscar_Puesto, tbl_Puesto);
        //puesto.Eliminar_Puesto();
    }//GEN-LAST:event_jLabel_Eliminar_PuestoMouseClicked

    private void Texto_IngresarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_IngresarPMouseClicked
        // TODO add your handling code here:
        jLabel_Eliminar_Puesto.setVisible(false);
        jLabel_Modificar_Puesto.setVisible(false);
        jLabel_Insertar_Puesto.setVisible(true);
    }//GEN-LAST:event_Texto_IngresarPMouseClicked

    private void Panel_IngresarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_IngresarPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_IngresarPMouseClicked

    private void Texto_ModificarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_ModificarPMouseClicked
        // TODO add your handling code here:
        jLabel_Modificar_Puesto.setVisible(true);
        jLabel_Insertar_Puesto.setVisible(false);
        jLabel_Eliminar_Puesto.setVisible(false);
    }//GEN-LAST:event_Texto_ModificarPMouseClicked

    private void Panel_ModificarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Panel_ModificarPMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Panel_ModificarPMouseClicked

    private void Texto_EliminarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_EliminarPMouseClicked
        // TODO add your handling code here:
        jLabel_Eliminar_Puesto.setVisible(true);
        jLabel_Modificar_Puesto.setVisible(false);
        jLabel_Insertar_Puesto.setVisible(false);
    }//GEN-LAST:event_Texto_EliminarPMouseClicked

    private void Texto_ConsultarPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Texto_ConsultarPMouseClicked
        // TODO add your handling code here:
        jLabel_Eliminar_Puesto.setVisible(false);
        jLabel_Modificar_Puesto.setVisible(false);
        jLabel_Insertar_Puesto.setVisible(false);
    }//GEN-LAST:event_Texto_ConsultarPMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_ConsultarP;
    private javax.swing.JPanel Panel_EliminarP;
    private javax.swing.JPanel Panel_IngresarP;
    private javax.swing.JPanel Panel_ModificarP;
    private javax.swing.JLabel Texto_ConsultarP;
    private javax.swing.JLabel Texto_EliminarP;
    private javax.swing.JLabel Texto_IngresarP;
    private javax.swing.JLabel Texto_ModificarP;
    private javax.swing.JButton btn_cerrar;
    private javax.swing.JButton btn_menu;
    private javax.swing.JLabel icono_Buscar1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_Buscar_Puesto;
    private javax.swing.JLabel jLabel_Descripcion_Puesto;
    private javax.swing.JLabel jLabel_Descripcion_Puesto1;
    private javax.swing.JLabel jLabel_Eliminar_Puesto;
    private javax.swing.JLabel jLabel_ID_Puesto;
    private javax.swing.JLabel jLabel_Insertar_Puesto;
    private javax.swing.JLabel jLabel_Modificar_Puesto;
    private javax.swing.JLabel jLabel_Nombre_Puesto;
    private javax.swing.JLabel jLabel_TituloD1;
    private javax.swing.JLabel jLabel_TituloD2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_MantenimientosP;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPanel pnl_menu;
    private javax.swing.JPanel pnl_registro;
    private javax.swing.JTable tbl_Puesto;
    private javax.swing.JTextField txt_Buscar_Puesto;
    private javax.swing.JTextArea txt_Descripcion_Puesto;
    private javax.swing.JTextField txt_Estatus_Puesto;
    private javax.swing.JTextField txt_Nombre_Puesto;
    private javax.swing.JTextField txt_apereg;
    private javax.swing.JTextField txt_id_Puesto;
    private javax.swing.JTextField txt_nombrereg;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_segapegreg;
    private javax.swing.JTextField txt_segnombrereg;
    private javax.swing.JTextField txt_user;
    // End of variables declaration//GEN-END:variables
}
